# Generated by Django 5.2.3 on 2025-06-15 14:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Contractor',
                'verbose_name_plural': 'Contractors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Creditor',
                'verbose_name_plural': 'Creditors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grower',
            fields=[
                ('grower_number', models.CharField(help_text='Unique Grower ID, e.g., V100081', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('farming_province', models.CharField(blank=True, max_length=100)),
                ('farm_name', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('registered_since', models.DateField(blank=True, null=True)),
                ('first_sales_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Grower',
                'verbose_name_plural': 'Growers',
                'ordering': ['surname', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.PositiveIntegerField(help_text='The year of the season, e.g., 2024')),
                ('estimated_dry_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_dry_hectrage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_irrigated_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_irrigated_hectrage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_bales', models.PositiveIntegerField(blank=True, null=True)),
                ('total_mass_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_value_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('average_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasonal_reports', to='growers.contractor')),
                ('grower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_reports', to='growers.grower')),
            ],
            options={
                'verbose_name': 'Seasonal Report',
                'verbose_name_plural': 'Seasonal Reports',
                'ordering': ['-season_year'],
                'unique_together': {('grower', 'season_year')},
            },
        ),
        migrations.CreateModel(
            name='GradeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=100)),
                ('mass_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('average_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seasonal_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_analysis_items', to='growers.seasonalreport')),
            ],
            options={
                'verbose_name': 'Grade Analysis',
                'verbose_name_plural': 'Grade Analyses',
            },
        ),
        migrations.CreateModel(
            name='CreditorRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_owed_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_paid_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recovery_percentage', models.DecimalField(decimal_places=2, help_text='Recovery percentage, e.g., 49.57', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='growers.creditor')),
                ('seasonal_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditor_recoveries', to='growers.seasonalreport')),
            ],
            options={
                'verbose_name': 'Creditor Recovery',
                'verbose_name_plural': 'Creditor Recoveries',
            },
        ),
    ]
