# Generated by Django 5.2.3 on 2025-06-19 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditorrecovery',
            name='recovery_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Recovery percentage, e.g., 49.57', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='creditorrecovery',
            name='total_owed_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='creditorrecovery',
            name='total_paid_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
